spring.application.name=api-gateway
server.port=8080

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka

spring.cloud.gateway.routes[0].id=student-service
spring.cloud.gateway.routes[0].uri=lb://student
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/students/**

spring.cloud.gateway.routes[1].id=course-service
spring.cloud.gateway.routes[1].uri=lb://course
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/course/**

spring.cloud.gateway.routes[2].id=enrollment-service
spring.cloud.gateway.routes[2].uri=lb://enrollement
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/enrollment/**

spring.cloud.gateway.default-filters[0]=DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-origins=http://localhost:3000
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-headers=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allow-credentials=false